/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002114",
        "background": "#f9f9ff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-background": "#151c27",
        "inverse-primary": "#b5c4ff",
        "tertiary-fixed": "#85f8c4",
        "on-tertiary-fixed-variant": "#005137",
        "on-primary-fixed": "#00174d",
        "primary": "#003fb1",
        "on-secondary-fixed": "#25005a",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed-variant": "#5a00c6",
        "tertiary-fixed-dim": "#68dba9",
        "surface-container-highest": "#dce2f3",
        "on-surface-variant": "#434654",
        "surface": "#f9f9ff",
        "tertiary-container": "#006f4d",
        "surface-tint": "#1353d8",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#ebf1ff",
        "outline-variant": "#c3c5d7",
        "secondary": "#7127e5",
        "primary-container": "#1a56db",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7ff2be",
        "on-primary-container": "#d4dcff",
        "primary-fixed-dim": "#b5c4ff",
        "error": "#ba1a1a",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#dce2f3",
        "surface-container-low": "#f0f3ff",
        "on-primary": "#ffffff",
        "on-surface": "#151c27",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#eaddff",
        "on-primary-fixed-variant": "#003dab",
        "tertiary": "#005439",
        "outline": "#737686",
        "inverse-surface": "#2a313d",
        "on-secondary-container": "#fffbff",
        "error-container": "#ffdad6",
        "surface-dim": "#d3daea",
        "secondary-container": "#8b4aff",
        "on-error": "#ffffff",
        "surface-container-high": "#e2e8f8",
        "surface-container": "#e7eefe"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
